use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// The fixed refusal returned when nothing is admitted. Never generated by a model.
pub const EMPTY_ADMIT_TEXT: &str = "I do not have that.";

#[derive(Debug, Deserialize)]
pub struct AskRequest {
    pub question: String,
    #[serde(default)]
    pub as_of: Option<DateTime<Utc>>,
    pub brain_id: Uuid,
    #[serde(default)]
    pub trace_id: Option<Uuid>,
}

impl AskRequest {
    pub fn validate(&self) -> Result<(), &'static str> {
        match self.question.trim().chars().count() {
            0 => Err("question must not be empty"),
            n if n > 4000 => Err("question must be at most 4000 characters"),
            _ => Ok(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum FilterRoute {
    Include,
    Conflict,
    Exclude,
}

/// A chunk returned by retrieval, before admission has judged it.
#[derive(Debug, Clone)]
pub struct Candidate {
    pub id: Uuid,
    pub statement: String,
    pub text: String,
    pub origin: String,
    pub grantor_name: Option<String>,
    pub source: Option<String>,
    pub occurred_at: Option<DateTime<Utc>>,
    pub rrf_score: f64,
    pub noul: Option<f64>,
    pub injection: Option<f64>,
    pub contradicts: Option<f64>,
    pub relevant: Option<f64>,
    pub evidence: Option<f64>,
    pub route: Option<FilterRoute>,
}

#[derive(Debug, Clone, Serialize)]
pub struct Citation {
    pub id: Uuid,
    pub index: usize,
    pub statement: String,
    pub noul: f64,
    pub origin: String,
    pub grantor_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub occurred_at: Option<DateTime<Utc>>,
    pub route: FilterRoute,
    #[serde(skip)]
    pub text: String,
}

/// Non-empty by construction: includes, conflicts, or both.
///
/// Conflict-only generate is allowed so a memory that refutes the question's
/// premise is not hidden behind empty-admit. Still no unfiltered RAG: every
/// fence came through the filter.
#[derive(Debug, Clone)]
pub struct AdmittedCitations {
    includes: Vec<Citation>,
    conflicts: Vec<Citation>,
}

impl AdmittedCitations {
    pub fn new(includes: Vec<Citation>, conflicts: Vec<Citation>) -> Option<Self> {
        if includes.is_empty() && conflicts.is_empty() {
            None
        } else {
            Some(Self {
                includes,
                conflicts,
            })
        }
    }

    pub fn includes(&self) -> &[Citation] {
        &self.includes
    }

    pub fn conflicts(&self) -> &[Citation] {
        &self.conflicts
    }

    pub fn all(&self) -> impl Iterator<Item = &Citation> {
        self.includes.iter().chain(self.conflicts.iter())
    }

    pub fn len(&self) -> usize {
        self.includes.len() + self.conflicts.len()
    }

    pub fn by_index(&self, i: usize) -> Option<&Citation> {
        self.all().find(|c| c.index == i)
    }
}

#[derive(Debug, Clone, Serialize)]
pub struct ClaimVerdict {
    pub claim: String,
    pub verdict: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub memory_index: Option<usize>,
}

#[derive(Debug)]
pub struct Ask {
    pub ask_id: Uuid,
    pub brain_id: Uuid,
    pub trace_id: Option<Uuid>,
    pub question: String,
    pub as_of: Option<DateTime<Utc>>,

    pub kind: Option<String>,
    pub kind_confidence: Option<f64>,
    pub chitchat: bool,

    pub embedding: Option<Vec<f32>>,
    pub candidates: Vec<Candidate>,
    pub admitted: Vec<Citation>,
    pub conflicts: Vec<Citation>,
    pub answer: Option<String>,
    pub empty: bool,
    pub verdicts: Vec<ClaimVerdict>,
    pub stages: Vec<StageRecord>,
}

impl Ask {
    pub fn new(req: AskRequest) -> Self {
        Self {
            ask_id: Uuid::new_v4(),
            brain_id: req.brain_id,
            trace_id: req.trace_id,
            question: req.question,
            as_of: req.as_of,
            kind: None,
            kind_confidence: None,
            chitchat: false,
            embedding: None,
            candidates: Vec::new(),
            admitted: Vec::new(),
            conflicts: Vec::new(),
            answer: None,
            empty: false,
            verdicts: Vec::new(),
            stages: Vec::new(),
        }
    }

    pub fn into_empty_admit(mut self) -> Self {
        self.empty = true;
        self.answer = Some(EMPTY_ADMIT_TEXT.to_string());
        self.admitted.clear();
        self.conflicts.clear();
        self
    }

    pub fn as_of_or_now(&self) -> DateTime<Utc> {
        self.as_of.unwrap_or_else(Utc::now)
    }

    pub fn citations_for_generate(&self) -> Option<AdmittedCitations> {
        AdmittedCitations::new(self.admitted.clone(), self.conflicts.clone())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Stage {
    Kind,
    Embed,
    Retrieve,
    Admit,
    Generate,
    Verify,
}

impl Stage {
    pub fn as_str(&self) -> &'static str {
        match self {
            Stage::Kind => "kind",
            Stage::Embed => "embed",
            Stage::Retrieve => "retrieve",
            Stage::Admit => "admit",
            Stage::Generate => "generate",
            Stage::Verify => "verify",
        }
    }
}

impl std::fmt::Display for Stage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StageRecord {
    pub stage: Stage,
    pub ms: u64,
    pub ok: bool,
}

#[derive(Debug, Serialize)]
pub struct AdmittedEvent<'a> {
    pub citations: &'a [Citation],
    pub candidate_count: usize,
}

#[derive(Debug, Serialize)]
pub struct SyncResponse {
    pub ask_id: Uuid,
    pub text: String,
    pub citations: Vec<Citation>,
    pub empty: bool,
    pub usage: serde_json::Value,
}
