use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// The fixed refusal returned when nothing is admitted. Never generated by a model.
pub const EMPTY_ADMIT_TEXT: &str = "I do not have that.";

#[derive(Debug, Deserialize)]
pub struct AskRequest {
    pub question: String,
    #[serde(default)]
    pub as_of: Option<DateTime<Utc>>,
    pub brain_id: Uuid,
    #[serde(default)]
    pub trace_id: Option<Uuid>,
}

impl AskRequest {
    pub fn validate(&self) -> Result<(), &'static str> {
        match self.question.trim().chars().count() {
            0 => Err("question must not be empty"),
            n if n > 4000 => Err("question must be at most 4000 characters"),
            _ => Ok(()),
        }
    }
}

/// A chunk returned by retrieval, before admission has judged it.
#[derive(Debug, Clone)]
pub struct Candidate {
    pub id: Uuid,
    pub statement: String,
    pub text: String,
    pub origin: String,
    pub grantor_name: Option<String>,
    /// Provenance carried through from the mounted rows, untouched.
    pub source: Option<String>,
    pub occurred_at: Option<DateTime<Utc>>,
    pub rrf_score: f64,
    /// Filled in by the admit stage.
    pub noul: Option<f64>,
}

#[derive(Debug, Clone, Serialize)]
pub struct Citation {
    pub id: Uuid,
    pub index: usize,
    pub statement: String,
    pub noul: f64,
    pub origin: String,
    pub grantor_name: Option<String>,
    /// Provenance from the mounted rows, passed through so the client can show where
    /// a granted memory came from and when it happened.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub occurred_at: Option<DateTime<Utc>>,
    /// Not serialized to clients; the generator needs the full text to answer from.
    #[serde(skip)]
    pub text: String,
}

/// Non-empty by construction.
///
/// This type is the enforcement of the one product rule that cannot be allowed to
/// break: the generator is never invoked without admitted evidence. `generate` takes
/// an `AdmittedCitations`, and the only way to obtain one is through `new`, which
/// refuses an empty set. There is no `Default`, no public field, and no other
/// constructor, so "generate without admission" does not typecheck.
#[derive(Debug, Clone)]
pub struct AdmittedCitations(Vec<Citation>);

impl AdmittedCitations {
    pub fn new(citations: Vec<Citation>) -> Option<Self> {
        if citations.is_empty() {
            None
        } else {
            Some(Self(citations))
        }
    }

    pub fn as_slice(&self) -> &[Citation] {
        &self.0
    }

    pub fn len(&self) -> usize {
        self.0.len()
    }
}

/// The state that moves from stage to stage. Never serialized between stages, so the
/// stage marker lives in `Ask::stages` as runtime data rather than in the type.
#[derive(Debug)]
pub struct Ask {
    pub ask_id: Uuid,
    pub brain_id: Uuid,
    pub trace_id: Option<Uuid>,
    pub question: String,
    pub as_of: Option<DateTime<Utc>>,

    pub embedding: Option<Vec<f32>>,
    pub candidates: Vec<Candidate>,
    pub admitted: Vec<Citation>,
    pub answer: Option<String>,
    pub empty: bool,
    pub stages: Vec<StageRecord>,
}

impl Ask {
    pub fn new(req: AskRequest) -> Self {
        Self {
            ask_id: Uuid::new_v4(),
            brain_id: req.brain_id,
            trace_id: req.trace_id,
            question: req.question,
            as_of: req.as_of,
            embedding: None,
            candidates: Vec::new(),
            admitted: Vec::new(),
            answer: None,
            empty: false,
            stages: Vec::new(),
        }
    }

    /// The terminal state for an ask whose admission came back empty. No generator call.
    pub fn into_empty_admit(mut self) -> Self {
        self.empty = true;
        self.answer = Some(EMPTY_ADMIT_TEXT.to_string());
        self.admitted.clear();
        self
    }

    pub fn as_of_or_now(&self) -> DateTime<Utc> {
        self.as_of.unwrap_or_else(Utc::now)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Stage {
    Embed,
    Retrieve,
    Admit,
    Generate,
}

impl Stage {
    pub fn as_str(&self) -> &'static str {
        match self {
            Stage::Embed => "embed",
            Stage::Retrieve => "retrieve",
            Stage::Admit => "admit",
            Stage::Generate => "generate",
        }
    }
}

impl std::fmt::Display for Stage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StageRecord {
    pub stage: Stage,
    pub ms: u64,
    pub ok: bool,
}

/// Body of the `admitted` SSE event and of the sync response's citation list.
#[derive(Debug, Serialize)]
pub struct AdmittedEvent<'a> {
    pub citations: &'a [Citation],
    pub candidate_count: usize,
}

#[derive(Debug, Serialize)]
pub struct SyncResponse {
    pub ask_id: Uuid,
    pub text: String,
    pub citations: Vec<Citation>,
    pub empty: bool,
    pub usage: serde_json::Value,
}
